#!/usr/bin/env python3
"""Build the offline loader fallback from the game's pinned CJK font.

Regenerate with fonttools[woff]==4.60.2, then run node web/build-shell.mjs.
Use --check to verify current source, actual glyph coverage and generated bytes.
"""

import argparse
import base64
import hashlib
import io
import json
from pathlib import Path

import fontTools
from fontTools import subset
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parents[1]
SOURCE = "assets/fonts/ManusCC0SansCJKSC-Regular.woff2"
SOURCE_SHA256 = "0a4981b817d7fb556dd8cd80f278483f1849017a312ca965e027d8e0e066968c"
LICENSE = "assets/fonts/ManusCC0-CJK-LICENSE.txt"
PRIMARY_HASHES = {
    "Regular": "b5124032e8e51434e05a51c327a9a614ac96b85ecf9b6cdcfc58834a9ae1347d",
    "Medium": "f28a0f3aee8f427798bf972504d5640d5d28b8692a73102ac39556fa7ffb1ee2",
    "Bold": "099f6d50114f83533f689ddc37028fcff2bd2a2c4871a332488c1a433f440804",
}


def digest(data):
    return hashlib.sha256(data).hexdigest()


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    if fontTools.__version__ != "4.60.2":
        raise SystemExit("Use fonttools[woff]==4.60.2 for reproducible loader fonts.")

    source = (ROOT / SOURCE).read_bytes()
    assert digest(source) == SOURCE_SHA256, "Pinned CJK source changed"
    lock = json.loads((ROOT / "assets.lock.json").read_text())["assets"][SOURCE]
    assert lock["sha256"] == "sha256:" + SOURCE_SHA256
    assert lock["size"] == len(source)
    primary_codepoints = None
    for weight, expected in PRIMARY_HASHES.items():
        data = (ROOT / f"assets/fonts/ManusCC0-{weight}.ttf").read_bytes()
        assert digest(data) == expected, f"Approved ManusCC0 {weight} changed"
        current = set(TTFont(io.BytesIO(data)).getBestCmap())
        primary_codepoints = current if primary_codepoints is None else primary_codepoints & current

    catalogs = {
        locale: {key: value for key, value in json.loads((ROOT / f"localization/{locale}.json").read_text()).items() if key.startswith("web.")}
        for locale in ["en", "zh-CN"]
    }
    corpus = "".join(value for catalog in catalogs.values() for value in catalog.values())
    # Include non-ASCII status/error punctuation authored outside the catalogs.
    for path in ["web/loader.js", "web/i18n.js", "web/loader.css"]:
        corpus += "".join(character for character in (ROOT / path).read_text() if ord(character) > 127)
    required = sorted({ord(character) for character in corpus if not character.isspace()} - primary_codepoints)
    font = TTFont(io.BytesIO(source), recalcTimestamp=False)
    missing = set(required) - set(font.getBestCmap())
    assert not missing, f"Pinned fallback lacks codepoints: {sorted(missing)}"
    options = subset.Options()
    options.recalc_timestamp = False
    options.name_IDs = ["*"]
    subsetter = subset.Subsetter(options=options)
    subsetter.populate(unicodes=required)
    subsetter.subset(font)
    font.flavor = "woff2"
    output = io.BytesIO()
    font.save(output, reorderTables=True)
    binary = output.getvalue()
    actual = sorted(TTFont(io.BytesIO(binary)).getBestCmap())
    assert set(required) <= set(actual), "Generated WOFF2 lost required glyphs"
    license_text = "ManusCC0 Sans CJK SC; CC0-1.0; notices optional."
    assert "*/" not in license_text
    css = (
        "/* Generated by tools/build-loader-cjk-font.py.\n"
        "Project-specific subset; primary typography remains ManusCC0.\n"
        + license_text + "\n*/\n"
        + '@font-face{font-family:ManusCC0CJKSC;src:url("data:font/woff2;base64,'
        + base64.b64encode(binary).decode("ascii")
        + '") format("woff2");font-style:normal;font-weight:100 900;font-display:swap}\n'
    )
    metadata = {
        "source": SOURCE,
        "sourceSha256": SOURCE_SHA256,
        "sourceUrl": lock["path"],
        "license": LICENSE,
        "licenseSha256": digest(license_text.encode()),
        "primarySha256": PRIMARY_HASHES,
        "fontToolsVersion": fontTools.__version__,
        "corpusSha256": digest(corpus.encode()),
        "requiredCodepoints": required,
        "outputCodepoints": actual,
        "woff2Sha256": digest(binary),
        "woff2Bytes": len(binary),
        "cssSha256": digest(css.encode()),
    }
    outputs = {
        "web/manus-fonts.css": css,
        "web/loader-font-source.json": json.dumps(metadata, indent=2, ensure_ascii=False) + "\n",
    }
    for path, text in outputs.items():
        if args.check:
            assert (ROOT / path).read_text() == text, f"Regenerate {path}"
        else:
            (ROOT / path).write_text(text)
    print(f"{'Verified' if args.check else 'Built'} offline CJK loader: {len(required)} codepoints, {len(binary)} WOFF2 bytes.")


if __name__ == "__main__":
    main()
